######################################################################
# Automatically generated by qmake (3.1) Wed May 29 06:38:25 2019
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += cryptanalysevig.h \
           DecryptWindow.h \
           deroulementcryptanalysesub.h \
           deroulementcryptanalysesubstitution.h \
           deroulementcryptsub.h \
           deroulementvigenere.h \
           EncryptWindow.h \
           gestfichier.h \
           Key.h \
           KeyS.h \
           KeyV.h \
           MainWindow.h \
           Polygramme.h \
           ResultWindow.h \
           test.h \
           Text.h \
           TextS.h \
           TextV.h \
           ui_cryptanalysevig.h \
           ui_deroulementcryptanalysesub.h \
           ui_deroulementcryptsub.h \
           ui_deroulementvigenere.h
FORMS += cryptanalysevig.ui \
         deroulementcryptanalysesub.ui \
         deroulementcryptsub.ui \
         deroulementvigenere.ui
SOURCES += cryptanalysevig.cpp \
           DecryptWindow.cpp \
           deroulementcryptanalysesub.cpp \
           deroulementcryptanalysesubstitution.cpp \
           deroulementcryptsub.cpp \
           deroulementvigenere.cpp \
           EncryptWindow.cpp \
           fenetre.cpp \
           gestfichiers.cpp \
           Key.cpp \
           KeyS.cpp \
           KeyV.cpp \
           main.cpp \
           MainWindow.cpp \
           Polygramme.cpp \
           ResultWindow.cpp \
           test.cpp \
           Text.cpp \
           TextS.cpp \
           TextV.cpp
